/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Vitals {
    weight?: number;
    temperature?: number;
    bloodPressure?: string;
    pulse?: bigint;
}
export interface ClinicalVisit {
    id: bigint;
    patientId: bigint;
    date: bigint;
    diagnosis: string;
    symptoms: Array<string>;
    treatmentPlan: Array<string>;
    vitals: Vitals;
}
export interface Medicine {
    duration: string;
    dosage: string;
    name: string;
    frequency: string;
}
export interface FollowUp {
    id: bigint;
    patientId: bigint;
    completed: boolean;
    appointmentDate: bigint;
    notes: string;
}
export interface Prescription {
    id: bigint;
    patientId: bigint;
    date: bigint;
    visitId: bigint;
    doctorName: string;
    medicines: Array<Medicine>;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface Patient {
    id: bigint;
    age: bigint;
    name: string;
    medicalHistory: Array<string>;
    address: string;
    gender: Gender;
    contactNumber: string;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelFollowUp(id: bigint): Promise<void>;
    createClinicalVisit(patientId: bigint, date: bigint, symptoms: Array<string>, diagnosis: string, treatmentPlan: Array<string>, vitals: Vitals): Promise<bigint>;
    createPrescription(patientId: bigint, visitId: bigint, medicines: Array<Medicine>, doctorName: string, date: bigint): Promise<bigint>;
    getAllFollowUps(): Promise<Array<FollowUp>>;
    getAllPatients(): Promise<Array<Patient>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClinicalHistory(patientId: bigint): Promise<Array<ClinicalVisit>>;
    getPatientById(id: bigint): Promise<Patient | null>;
    getPrescriptionById(id: bigint): Promise<Prescription | null>;
    getPrescriptionsByPatient(patientId: bigint): Promise<Array<Prescription>>;
    getUpcomingFollowUps(patientId: bigint): Promise<Array<FollowUp>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisitById(id: bigint): Promise<ClinicalVisit | null>;
    isCallerAdmin(): Promise<boolean>;
    markFollowUpCompleted(id: bigint): Promise<void>;
    registerPatient(name: string, age: bigint, gender: Gender, contactNumber: string, address: string, medicalHistory: Array<string>): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    scheduleFollowUp(patientId: bigint, appointmentDate: bigint, notes: string): Promise<bigint>;
    searchPatientsByContact(contact: string): Promise<Array<Patient>>;
    searchPatientsByName(name: string): Promise<Array<Patient>>;
    updatePatient(id: bigint, name: string, age: bigint, gender: Gender, contactNumber: string, address: string, medicalHistory: Array<string>): Promise<void>;
    updatePrescription(id: bigint, medicines: Array<Medicine>, doctorName: string): Promise<void>;
    updateVisit(id: bigint, symptoms: Array<string>, diagnosis: string, treatmentPlan: Array<string>, vitals: Vitals): Promise<void>;
}
import type { ClinicalVisit as _ClinicalVisit, Gender as _Gender, Patient as _Patient, Prescription as _Prescription, UserProfile as _UserProfile, UserRole as _UserRole, Vitals as _Vitals } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelFollowUp(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelFollowUp(arg0);
            return result;
        }
    }
    async createClinicalVisit(arg0: bigint, arg1: bigint, arg2: Array<string>, arg3: string, arg4: Array<string>, arg5: Vitals): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClinicalVisit(arg0, arg1, arg2, arg3, arg4, to_candid_Vitals_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClinicalVisit(arg0, arg1, arg2, arg3, arg4, to_candid_Vitals_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createPrescription(arg0: bigint, arg1: bigint, arg2: Array<Medicine>, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrescription(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrescription(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllFollowUps(): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFollowUps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFollowUps();
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClinicalHistory(arg0: bigint): Promise<Array<ClinicalVisit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicalHistory(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicalHistory(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientById(arg0: bigint): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescriptionById(arg0: bigint): Promise<Prescription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionById(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionById(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescriptionsByPatient(arg0: bigint): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionsByPatient(arg0);
            return result;
        }
    }
    async getUpcomingFollowUps(arg0: bigint): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingFollowUps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingFollowUps(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitById(arg0: bigint): Promise<ClinicalVisit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitById(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitById(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markFollowUpCompleted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markFollowUpCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFollowUpCompleted(arg0);
            return result;
        }
    }
    async registerPatient(arg0: string, arg1: bigint, arg2: Gender, arg3: string, arg4: string, arg5: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPatient(arg0, arg1, to_candid_Gender_n24(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPatient(arg0, arg1, to_candid_Gender_n24(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async scheduleFollowUp(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleFollowUp(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleFollowUp(arg0, arg1, arg2);
            return result;
        }
    }
    async searchPatientsByContact(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatientsByContact(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatientsByContact(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchPatientsByName(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatientsByName(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatientsByName(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePatient(arg0: bigint, arg1: string, arg2: bigint, arg3: Gender, arg4: string, arg5: string, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1, arg2, to_candid_Gender_n24(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1, arg2, to_candid_Gender_n24(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async updatePrescription(arg0: bigint, arg1: Array<Medicine>, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrescription(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrescription(arg0, arg1, arg2);
            return result;
        }
    }
    async updateVisit(arg0: bigint, arg1: Array<string>, arg2: string, arg3: Array<string>, arg4: Vitals): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisit(arg0, arg1, arg2, arg3, to_candid_Vitals_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisit(arg0, arg1, arg2, arg3, to_candid_Vitals_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_ClinicalVisit_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClinicalVisit): ClinicalVisit {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Vitals_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vitals): Vitals {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : from_candid_Patient_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Prescription]): Prescription | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClinicalVisit]): ClinicalVisit | null {
    return value.length === 0 ? null : from_candid_ClinicalVisit_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    patientId: bigint;
    date: bigint;
    diagnosis: string;
    symptoms: Array<string>;
    treatmentPlan: Array<string>;
    vitals: _Vitals;
}): {
    id: bigint;
    patientId: bigint;
    date: bigint;
    diagnosis: string;
    symptoms: Array<string>;
    treatmentPlan: Array<string>;
    vitals: Vitals;
} {
    return {
        id: value.id,
        patientId: value.patientId,
        date: value.date,
        diagnosis: value.diagnosis,
        symptoms: value.symptoms,
        treatmentPlan: value.treatmentPlan,
        vitals: from_candid_Vitals_n16(_uploadFile, _downloadFile, value.vitals)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: [] | [number];
    temperature: [] | [number];
    bloodPressure: [] | [string];
    pulse: [] | [bigint];
}): {
    weight?: number;
    temperature?: number;
    bloodPressure?: string;
    pulse?: bigint;
} {
    return {
        weight: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.weight)),
        temperature: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.temperature)),
        bloodPressure: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.bloodPressure)),
        pulse: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.pulse))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    name: string;
    medicalHistory: Array<string>;
    address: string;
    gender: _Gender;
    contactNumber: string;
}): {
    id: bigint;
    age: bigint;
    name: string;
    medicalHistory: Array<string>;
    address: string;
    gender: Gender;
    contactNumber: string;
} {
    return {
        id: value.id,
        age: value.age,
        name: value.name,
        medicalHistory: value.medicalHistory,
        address: value.address,
        gender: from_candid_Gender_n8(_uploadFile, _downloadFile, value.gender),
        contactNumber: value.contactNumber
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClinicalVisit>): Array<ClinicalVisit> {
    return value.map((x)=>from_candid_ClinicalVisit_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Vitals_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vitals): _Vitals {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight?: number;
    temperature?: number;
    bloodPressure?: string;
    pulse?: bigint;
}): {
    weight: [] | [number];
    temperature: [] | [number];
    bloodPressure: [] | [string];
    pulse: [] | [bigint];
} {
    return {
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        temperature: value.temperature ? candid_some(value.temperature) : candid_none(),
        bloodPressure: value.bloodPressure ? candid_some(value.bloodPressure) : candid_none(),
        pulse: value.pulse ? candid_some(value.pulse) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
