/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClinicalVisit {
  'id' : bigint,
  'patientId' : bigint,
  'date' : bigint,
  'diagnosis' : string,
  'symptoms' : Array<string>,
  'treatmentPlan' : Array<string>,
  'vitals' : Vitals,
}
export interface FollowUp {
  'id' : bigint,
  'patientId' : bigint,
  'completed' : boolean,
  'appointmentDate' : bigint,
  'notes' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Medicine {
  'duration' : string,
  'dosage' : string,
  'name' : string,
  'frequency' : string,
}
export interface Patient {
  'id' : bigint,
  'age' : bigint,
  'name' : string,
  'medicalHistory' : Array<string>,
  'address' : string,
  'gender' : Gender,
  'contactNumber' : string,
}
export interface Prescription {
  'id' : bigint,
  'patientId' : bigint,
  'date' : bigint,
  'visitId' : bigint,
  'doctorName' : string,
  'medicines' : Array<Medicine>,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vitals {
  'weight' : [] | [number],
  'temperature' : [] | [number],
  'bloodPressure' : [] | [string],
  'pulse' : [] | [bigint],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelFollowUp' : ActorMethod<[bigint], undefined>,
  'createClinicalVisit' : ActorMethod<
    [bigint, bigint, Array<string>, string, Array<string>, Vitals],
    bigint
  >,
  'createPrescription' : ActorMethod<
    [bigint, bigint, Array<Medicine>, string, bigint],
    bigint
  >,
  'getAllFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClinicalHistory' : ActorMethod<[bigint], Array<ClinicalVisit>>,
  'getPatientById' : ActorMethod<[bigint], [] | [Patient]>,
  'getPrescriptionById' : ActorMethod<[bigint], [] | [Prescription]>,
  'getPrescriptionsByPatient' : ActorMethod<[bigint], Array<Prescription>>,
  'getUpcomingFollowUps' : ActorMethod<[bigint], Array<FollowUp>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitById' : ActorMethod<[bigint], [] | [ClinicalVisit]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markFollowUpCompleted' : ActorMethod<[bigint], undefined>,
  'registerPatient' : ActorMethod<
    [string, bigint, Gender, string, string, Array<string>],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleFollowUp' : ActorMethod<[bigint, bigint, string], bigint>,
  'searchPatientsByContact' : ActorMethod<[string], Array<Patient>>,
  'searchPatientsByName' : ActorMethod<[string], Array<Patient>>,
  'updatePatient' : ActorMethod<
    [bigint, string, bigint, Gender, string, string, Array<string>],
    undefined
  >,
  'updatePrescription' : ActorMethod<
    [bigint, Array<Medicine>, string],
    undefined
  >,
  'updateVisit' : ActorMethod<
    [bigint, Array<string>, string, Array<string>, Vitals],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];