/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Vitals = IDL.Record({
  'weight' : IDL.Opt(IDL.Float64),
  'temperature' : IDL.Opt(IDL.Float64),
  'bloodPressure' : IDL.Opt(IDL.Text),
  'pulse' : IDL.Opt(IDL.Nat),
});
export const Medicine = IDL.Record({
  'duration' : IDL.Text,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'frequency' : IDL.Text,
});
export const FollowUp = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'completed' : IDL.Bool,
  'appointmentDate' : IDL.Int,
  'notes' : IDL.Text,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'medicalHistory' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'gender' : Gender,
  'contactNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ClinicalVisit = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'date' : IDL.Int,
  'diagnosis' : IDL.Text,
  'symptoms' : IDL.Vec(IDL.Text),
  'treatmentPlan' : IDL.Vec(IDL.Text),
  'vitals' : Vitals,
});
export const Prescription = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'date' : IDL.Int,
  'visitId' : IDL.Nat,
  'doctorName' : IDL.Text,
  'medicines' : IDL.Vec(Medicine),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelFollowUp' : IDL.Func([IDL.Nat], [], []),
  'createClinicalVisit' : IDL.Func(
      [
        IDL.Nat,
        IDL.Int,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
        Vitals,
      ],
      [IDL.Nat],
      [],
    ),
  'createPrescription' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(Medicine), IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'getAllFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClinicalHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ClinicalVisit)],
      ['query'],
    ),
  'getPatientById' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
  'getPrescriptionById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Prescription)],
      ['query'],
    ),
  'getPrescriptionsByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getUpcomingFollowUps' : IDL.Func([IDL.Nat], [IDL.Vec(FollowUp)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitById' : IDL.Func([IDL.Nat], [IDL.Opt(ClinicalVisit)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markFollowUpCompleted' : IDL.Func([IDL.Nat], [], []),
  'registerPatient' : IDL.Func(
      [IDL.Text, IDL.Nat, Gender, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleFollowUp' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Nat], []),
  'searchPatientsByContact' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Patient)],
      ['query'],
    ),
  'searchPatientsByName' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
  'updatePatient' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        Gender,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updatePrescription' : IDL.Func(
      [IDL.Nat, IDL.Vec(Medicine), IDL.Text],
      [],
      [],
    ),
  'updateVisit' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text), IDL.Text, IDL.Vec(IDL.Text), Vitals],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Vitals = IDL.Record({
    'weight' : IDL.Opt(IDL.Float64),
    'temperature' : IDL.Opt(IDL.Float64),
    'bloodPressure' : IDL.Opt(IDL.Text),
    'pulse' : IDL.Opt(IDL.Nat),
  });
  const Medicine = IDL.Record({
    'duration' : IDL.Text,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'completed' : IDL.Bool,
    'appointmentDate' : IDL.Int,
    'notes' : IDL.Text,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'medicalHistory' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'gender' : Gender,
    'contactNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ClinicalVisit = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'date' : IDL.Int,
    'diagnosis' : IDL.Text,
    'symptoms' : IDL.Vec(IDL.Text),
    'treatmentPlan' : IDL.Vec(IDL.Text),
    'vitals' : Vitals,
  });
  const Prescription = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'date' : IDL.Int,
    'visitId' : IDL.Nat,
    'doctorName' : IDL.Text,
    'medicines' : IDL.Vec(Medicine),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelFollowUp' : IDL.Func([IDL.Nat], [], []),
    'createClinicalVisit' : IDL.Func(
        [
          IDL.Nat,
          IDL.Int,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
          Vitals,
        ],
        [IDL.Nat],
        [],
      ),
    'createPrescription' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(Medicine), IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'getAllFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClinicalHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ClinicalVisit)],
        ['query'],
      ),
    'getPatientById' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
    'getPrescriptionById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Prescription)],
        ['query'],
      ),
    'getPrescriptionsByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getUpcomingFollowUps' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FollowUp)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitById' : IDL.Func([IDL.Nat], [IDL.Opt(ClinicalVisit)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markFollowUpCompleted' : IDL.Func([IDL.Nat], [], []),
    'registerPatient' : IDL.Func(
        [IDL.Text, IDL.Nat, Gender, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleFollowUp' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Nat], []),
    'searchPatientsByContact' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Patient)],
        ['query'],
      ),
    'searchPatientsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Patient)],
        ['query'],
      ),
    'updatePatient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          Gender,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updatePrescription' : IDL.Func(
        [IDL.Nat, IDL.Vec(Medicine), IDL.Text],
        [],
        [],
      ),
    'updateVisit' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text), IDL.Text, IDL.Vec(IDL.Text), Vitals],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };